name: cli
on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: |
        echo: ${{ secrets.DOCKER_USERNAME }}
        echo: ${{ secrets.DOCKER_PASSWORD }}
        docker build -t app .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag app tapoos/igtest-down
        docker push tapoos/igtest-down
